FROM apache/airflow:2.10.4-python3.12

# Switch to root to install any necessary system dependencies
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch back to the airflow user
USER airflow

# Copy the requirements file from the host
COPY requirements.txt /tmp/requirements.txt

# Install the Python dependencies
# Adding dbt-bigquery to support dbt run commands from Airflow
# Run as root to avoid Read-only file system errors when updating system packages
USER root
RUN python -m pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /tmp/requirements.txt \
    && python -m pip install --no-cache-dir dbt-bigquery==1.8.2

# Switch back to the airflow user
USER airflow
